# Generated by Django 3.2.8 on 2021-10-28 17:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('max_people', models.PositiveSmallIntegerField(verbose_name='maximum of people')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'room typology',
                'verbose_name_plural': 'room typologies',
                'db_table': 'misc_room_typology',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('room_typology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.roomtypology', verbose_name='room typology')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'misc_room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('guests', models.PositiveSmallIntegerField(verbose_name='guests')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('price', models.FloatField(verbose_name='price')),
                ('locator', models.CharField(max_length=16, verbose_name='locator')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.room', verbose_name='room')),
                ('room_typology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.roomtypology', verbose_name='room typology')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'db_table': 'misc_reservation',
            },
        ),
    ]
