# Generated by Django 3.2.8 on 2021-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pendent', 'Pendent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('not_executed', 'Not executed')], default='pendent', max_length=12, verbose_name='status'),
            preserve_default=False,
        ),
    ]
