# Generated by Django 3.2.8 on 2021-11-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpleasantCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('reason', models.TextField(verbose_name='reason')),
            ],
            options={
                'verbose_name': 'unpleasant customer',
                'verbose_name_plural': 'unpleasant customers',
                'db_table': 'misc_unpleasant_customer',
            },
        ),
    ]
