# Generated by Django 3.2.8 on 2021-11-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_unpleasantcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unpleasantcustomer',
            options={'ordering': ('email',), 'verbose_name': 'unpleasant customer', 'verbose_name_plural': 'unpleasant customers'},
        ),
    ]
