# Generated by Django 3.2.8 on 2021-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_unpleasantcustomer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpleasantcustomer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
