# Generated by Django 3.2.8 on 2021-10-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20211029_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('start_date',), 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
